Update Lineage-v2.yml

diff --git a/.github/workflows/Lineage-v2.yml b/.github/workflows/Lineage-v2.yml
--- a/.github/workflows/Lineage-v2.yml
+++ b/.github/workflows/Lineage-v2.yml
@@ -1,5 +1,4 @@
-name: LOS v2
-
+name: LOS V2
 on:
   workflow_dispatch:
     inputs:
@@ -20,38 +19,37 @@ on:
         required: true
         default: 'vayu_user_defconfig'
       TOOLCHAIN_URL:
-        description: "Clone URL of your toolchain or tarball URL"
+        description: "Clone URL of your toolchain"
         required: true
         default: 'https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r530567.git -b 14.0'
       ANYKERNEL:
-        description: "Clone URL of your AnyKernel including branch"
+        description: "Clone URL of your AnyKernel"
         required: true
         default: 'https://github.com/muhdhaniff55/AnyKernel3.git -b anothermaster'
 
 jobs:
-  Kernel:
-    runs-on: ubuntu-24.04
+  Build_Kernel:
+    runs-on: ubuntu-latest
     permissions: write-all
     defaults:
       run:
-        shell: bash
-        working-directory: ${{ github.workspace }}
+       shell: bash
+       working-directory: ${{ github.workspace }}
 
     steps:
       - name: Set-up environment
         run: |
           rm -rf ${{ github.workspace }}/*
           sudo apt-get update
-          sudo apt-get install -y build-essential bc lld gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev llvm
-          sudo apt-get install -y curl git ftp lftp wget libarchive-tools ccache python3 python3-dev
+          sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev
+          sudo apt-get install -y curl git ftp lftp wget libarchive-tools ccache python-is-python3
           sudo apt-get install -y zip unzip tar gzip bzip2 rar unrar cpio jq
-          sudo apt-get install -y device-tree-compiler
-
+          
       - name: Cloning Kernel Source
         run: |
-          git clone --single-branch --depth=1 --no-tags ${{ github.event.inputs.KERNEL_SOURCE }} -b ${{ github.event.inputs.KERNEL_BRANCH }} ${{ github.workspace }}
-
-      - name: Cloning Toolchain
+          git clone --single-branch --depth=1 --no-tags ${{ github.event.inputs.KERNEL_SOURCE }} -b ${{ github.event.inputs.KERNEL_BRANCH }} ${{ github.workspace }}/kernel
+          
+      - name: Set-up Toolchain
         run: |
           TOOLCHAIN_URL="${{ github.event.inputs.TOOLCHAIN_URL }}"
           mkdir -p ${{ github.workspace }}/toolchain
@@ -69,104 +67,117 @@ jobs:
             git clone --single-branch --depth=1 --no-tags ${{ github.event.inputs.TOOLCHAIN_URL }} ${{ github.workspace }}/toolchain
           fi
 
-      - name: Set-up Cache
-        id: cache-out
-        uses: actions/cache@v4
-        with:
-          path: ${{ github.workspace }}/out
-          key: ${{ github.event.inputs.KERNEL_SOURCE }}-out-
+      - name: Set environment variables
+        run: |
+          echo "OBJDIR=${{ github.workspace }}/kernel/out" >> $GITHUB_ENV
+          echo "ANYKERNEL=${{ github.workspace }}/anykernel" >> $GITHUB_ENV
+          echo "CLANG_DIR=${{ github.workspace }}/toolchain" >> $GITHUB_ENV
+          echo "KERNEL_NAME=${{ github.event.inputs.KERNEL_NAME }}" >> $GITHUB_ENV
+          echo "ZIP_NAME=${{ github.event.inputs.KERNEL_NAME }}-$(date +"%d%m%Y").zip" >> $GITHUB_ENV
+          echo "OUTPUT_DIR=${{ github.workspace }}/compiled" >> $GITHUB_ENV
+          cd ${{ github.workspace }}/kernel && echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
 
+          KERNEL_SOURCE_URL="${{ github.event.inputs.KERNEL_SOURCE }}"
+          if [[ "${KERNEL_SOURCE_URL}" == *.git ]]; then
+            KERNEL_SOURCE_URL="${KERNEL_SOURCE_URL%.git}"
+          fi
+          echo "KERNEL_SOURCE_URL=${KERNEL_SOURCE_URL}" >> $GITHUB_ENV
+         
       - name: Start Compilation
         run: |
-          export TZ='Asia/Kuala_Lumpur'
-          
-          objdir="${{ github.workspace }}/out"
-          anykernel="${{ github.workspace }}/anykernel"
-          clang_dir="${{ github.workspace }}/toolchain"
-          kernel_name="${{ github.event.inputs.KERNEL_NAME }}"
-          zip_name="${kernel_name}-$(date +"%d-%m-%Y").zip"
-          arch="arm64"
-          export KBUILD_BUILD_HOST=Newehh
-          export KBUILD_BUILD_USER=home
-
-          export PATH="${clang_dir}/bin:$PATH"
-          
-          make_defconfig() {
+         mkdir -p ${{ env.OUTPUT_DIR }}
+         cd ${{ github.workspace }}/kernel
+         export TZ='Asia/Kuala_Lumpur'
+         export KBUILD_BUILD_HOST=Newehh
+         export KBUILD_BUILD_USER=home
+         
+         export PATH="${{ env.CLANG_DIR }}/bin:$PATH"
+         
+         make_defconfig() {
             start=$(date +"%s")
-            make -s ARCH=${arch} O=${objdir} ${{ github.event.inputs.CONFIG_FILE }} -j$(nproc --all)
-          }
-
-          compile() {
-            cd "${{ github.workspace }}"
-              
+            make -s ARCH=arm64 O=${{ env.OBJDIR }} ${{ github.event.inputs.CONFIG_FILE }} -j$(nproc --all)
+         }
+         
+         compile() {       
             make -j$(nproc --all) \
-              O=out \
-              ARCH="${arch}" \
-              SUBARCH=arm64 \
-              DTC_EXT=dtc \
-              CC=clang \
-              CLANG_TRIPLE=aarch64-linux-gnu- \
-              CROSS_COMPILE=aarch64-linux-gnu- \
-              CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
-              CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
-              LD=ld.lld \
-              AR=llvm-ar \
-              NM=llvm-nm \
-              STRIP=llvm-strip \
-              OBJCOPY=llvm-objcopy \
-              OBJDUMP=llvm-objdump \
-              READELF=llvm-readelf \
-              LLVM=1 \
-              LLVM_IAS=1
-          }
+            O=${{ env.OBJDIR }} \
+            ARCH=arm64 \
+            CC=clang \
+            CROSS_COMPILE=aarch64-linux-gnu- \
+            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
+            CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
+            AR=llvm-ar \
+            LLVM_NM=llvm-nm \
+            OBJCOPY=llvm-objcopy \
+            LD=ld.lld \
+            NM=llvm-nm \
+            LLVM=1 \
+            LLVM_IAS=1
+         }
 
-          completion() {
-            cd "${objdir}"
-            compiled_image="arch/arm64/boot/Image"
-            compiled_dtbo="arch/arm64/boot/dtbo.img"
+         make_defconfig
+         compile
 
-            git clone -q ${{ github.event.inputs.ANYKERNEL }} "$anykernel"
-            cp "${compiled_image}" "${{ github.workspace }}"
-            cp "${compiled_dtbo}" "${{ github.workspace }}"
-
-            mv -f "${compiled_image}" "$anykernel/Image"
-            mv -f "${compiled_dtbo}" "$anykernel/dtbo.img"
-            find arch/arm64/boot/dts/qcom/ -name "*.dtb" -exec cat {} + > "$anykernel/dtb"
-            cd "$anykernel"
-            zip -r AnyKernel.zip *
-            mv -- "AnyKernel.zip" "$zip_name"
-            mv -- "$anykernel/$zip_name" "${{ github.workspace }}/$zip_name"
-            rm -rf "$anykernel"
-            end=$(date +"%s")
-            diff=$((end - start))
-            echo -e "BUILD COMPLETED IN ${diff} SECONDS"
-          }
-
-          make_defconfig
-          compile
-          completion
-
-          cd "${{ github.workspace }}"
-
-          # Set-up file info
-          zip_file=$(find . -name '${{ github.event.inputs.KERNEL_NAME }}*.zip' -print -quit)
-          echo "ZIP_FILE=$zip_file" >> $GITHUB_ENV
-          echo "ZIP_NAME=$(basename "$zip_file" .zip)" >> $GITHUB_ENV
-          echo "RELEASE_DATE=$(TZ='Asia/Kuala_Lumpur' date +'%B %-d, %Y %H:%M')" >> $GITHUB_ENV
-          echo "DTBO=${{ github.workspace }}/dtbo.img" >> $GITHUB_ENV
-          echo "IMAGE=${{ github.workspace }}/Image" >> $GITHUB_ENV
+         end=$(date +"%s")
+         diff=$((end - start))
+         echo -e "BUILD COMPLETED IN ${diff} SECONDS"
 
         continue-on-error: false
+         
+      - name: Checking for outputs
+        run: |
+         cd "${{ env.OBJDIR }}"
+         
+         compiled_image="arch/arm64/boot/Image"
+         compiled_gz_image="arch/arm64/boot/Image.gz"
+         compiled_gz_dtb="arch/arm64/boot/Image.gz-dtb"
+         compiled_dtbo="arch/arm64/boot/dtbo.img"
+         qcom_dtb="arch/arm64/boot/dts/qcom"
+           
+         if [[ -f ${compiled_image} || -f ${compiled_gz_image} || -f ${compiled_gz_dtb} ]]; then
+              git clone -q ${{ github.event.inputs.ANYKERNEL }} "${{ env.ANYKERNEL }}"
+
+              if [[ -f "${compiled_image}" ]]; then
+                  cp -f "${compiled_image}" "${{ env.ANYKERNEL }}/Image" || true
+                  cp -f "${compiled_image}" "${{ env.OUTPUT_DIR }}/Image" || true
+              elif [[ -f "${compiled_gz_image}" ]]; then
+                  cp -f "${compiled_gz_image}" "${{ env.ANYKERNEL }}/Image.gz" || true
+                  cp -f "${compiled_gz_image}" "${{ env.OUTPUT_DIR }}/Image.gz" || true
+              elif [[ -f "${compiled_gz_dtb}" ]]; then
+                  cp -f "${compiled_gz_dtb}" "${{ env.ANYKERNEL }}/Image.gz-dtb" || true
+                  cp -f "${compiled_gz_dtb}" "${{ env.OUTPUT_DIR }}/Image.gz-dtb" || true
+              fi
+              
+              if [[ -f "${compiled_dtbo}" ]]; then
+                  cp -f "${compiled_dtbo}" "${{ env.ANYKERNEL }}/dtbo.img" || true
+                  cp -f "${compiled_dtbo}" "${{ env.OUTPUT_DIR }}/dtbo.img" || true
+              fi
+              
+              if ls ${qcom_dtb}/*.dtb 1> /dev/null 2>&1; then
+                  cp -f ${qcom_dtb}/*.dtb "${{ env.OUTPUT_DIR }}" || true
+              fi
+
+              cd "${{ env.ANYKERNEL }}"
+              zip -r AnyKernel.zip *
+              mv -- "AnyKernel.zip" "${{ env.ZIP_NAME }}"
+              mv -- "${{ env.ANYKERNEL }}/${{ env.ZIP_NAME }}" "${{ env.OUTPUT_DIR }}/${{ env.ZIP_NAME }}"
+              rm -rf "${{ env.ANYKERNEL }}"
+         else
+              echo "ERROR: Some output is missing!"
+              exit 1
+         fi
+         
+         zip_file=$(find ${{ env.OUTPUT_DIR }} -name '${{ github.event.inputs.KERNEL_NAME }}*.zip' -print -quit)
+         echo "ZIP_NAME=$(basename "$zip_file" .zip)" >> $GITHUB_ENV
+         echo "RELEASE_DATE=$(TZ='Asia/Kuala_Lumpur' date +'%B %-d, %Y %H:%M')" >> $GITHUB_ENV
 
       - name: Upload files to repository releases page
         uses: softprops/action-gh-release@v2
         with:
           files: |
-            ${{ github.workspace }}/*.dtb
-            ${{ env.ZIP_FILE }}
-            ${{ env.DTBO }}
-            ${{ env.IMAGE }}
-          name: ${{ env.ZIP_NAME }}
+            ${{ github.workspace }}/compiled/*
+          name: ${{ github.event.inputs.KERNEL_NAME }} // ${{ env.RELEASE_DATE }}
           tag_name: ${{ github.run_id }}
           body: |
-            Released on ${{ env.RELEASE_DATE }}
+            [Kernel Source](${{ env.KERNEL_SOURCE_URL }}/tree/${{ github.event.inputs.KERNEL_BRANCH }})
+            [Latest Commit](${{ env.KERNEL_SOURCE_URL }}/commit/${{ env.COMMIT_ID }}) at the time of building.
